### ISSUE TITLE
Support for memories/save states

### ISSUE THREAD

**Issue by bspinner** [Mazamars312/Analogue-Amiga#31]
It would be nice to be able to use the pocket‘s save state feauture.

I read somewhere that this is something hard to do for FPGA cores, if not done from the beginning, but wasn‘t able find it again.

**Comment by limi** [comment]
Yeah, it’s pretty much impossible to do with computer cores, since they have so much state compared to a console. Even the console cores that support it are written with it in mind before work starts, retrofitting it onto an existing core is usually very hard.

On the upside, many Amiga games have native save functions, which do work with e.g. https://amiga.vision.
