### ISSUE TITLE
Beneath a Steel Sky not working

### ISSUE THREAD

**Issue by ifighftdragons** [Mazamars312/Analogue-Amiga#6]
The game boots and plays the cinematic intro.
It then asks: Please Insert Disk 0

Inserting Disk 0 does nothing, and the game is stuck on a loop, continually asking for Disk 0 to be inserted.

Hopefully this can be fixed, as it's one of the best and most beloved Amiga games.

**Comment by Mazamars312** [comment]
Looks like this is a common issue with this game. I used 2 floppy drives with both disk 0 and 1 inserted to get this to boot.
Just remember no save games yet so this might also be part of this issue.
This is what I'm referencing https://www.lemonamiga.com/forum/viewtopic.php?t=805 So once I get hard drives working that might be interesting to see what happens there.

**Comment by limi** [comment]
For what it’s worth, this game seems to work perfectly using the https://amiga.vision setup if you don’t want to deal with all the configuration yourself.

Do note that the initial loading will take quite a while because it’s a large game that gets loaded into memory, and the Analogue Pocket has rather slow disk I/O speeds.

**Comment by limi** [comment]
Closing since this is working (and the bug was filed before the core had hard disk support), re-open if you still find issues.
